// This file is auto-generated by @hey-api/openapi-ts

export const AgentCreateSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        role_type: {
            type: 'string',
            title: 'Role Type'
        },
        human_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Human Name'
        }
    },
    type: 'object',
    required: ['project_id', 'role_type'],
    title: 'AgentCreate'
} as const;

export const AgentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        human_name: {
            type: 'string',
            title: 'Human Name'
        },
        role_type: {
            type: 'string',
            title: 'Role Type'
        },
        agent_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'human_name', 'role_type', 'id', 'project_id', 'status', 'created_at', 'updated_at'],
    title: 'AgentPublic'
} as const;

export const AgentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        human_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Human Name'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'AgentUpdate'
} as const;

export const AgentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentsPublic'
} as const;

export const ApproveRequestSchema = {
    properties: {
        approved: {
            type: 'boolean',
            title: 'Approved'
        },
        feedback: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feedback'
        }
    },
    type: 'object',
    required: ['approved'],
    title: 'ApproveRequest',
    description: 'Request to approve or refine phase output'
} as const;

export const AuthorTypeSchema = {
    type: 'string',
    enum: ['user', 'agent'],
    title: 'AuthorType'
} as const;

export const BlockerCreateSchema = {
    properties: {
        backlog_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Backlog Item Id'
        },
        blocker_type: {
            type: 'string',
            title: 'Blocker Type'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['backlog_item_id', 'blocker_type', 'description'],
    title: 'BlockerCreate'
} as const;

export const BlockerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        backlog_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Backlog Item Id'
        },
        reported_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reported By User Id'
        },
        blocker_type: {
            type: 'string',
            title: 'Blocker Type'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'backlog_item_id', 'reported_by_user_id', 'blocker_type', 'description', 'created_at'],
    title: 'BlockerPublic'
} as const;

export const BlockersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BlockerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BlockersPublic'
} as const;

export const Body_authentication_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_authentication-login_access_token'
} as const;

export const ChatMessageCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        author_type: {
            '$ref': '#/components/schemas/AuthorType'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        agent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Id'
        },
        message_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Type',
            default: 'text'
        },
        structured_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Structured Data'
        }
    },
    type: 'object',
    required: ['content', 'author_type', 'project_id'],
    title: 'ChatMessageCreate'
} as const;

export const ChatMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        author_type: {
            '$ref': '#/components/schemas/AuthorType'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        agent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        message_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Type',
            default: 'text'
        },
        structured_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Structured Data'
        },
        message_metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Metadata'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'author_type', 'content', 'created_at', 'updated_at'],
    title: 'ChatMessagePublic'
} as const;

export const ChatMessageUpdateSchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    title: 'ChatMessageUpdate'
} as const;

export const ChatMessagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatMessagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatMessagesPublic'
} as const;

export const ConfirmCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        code: {
            type: 'string',
            maxLength: 6,
            minLength: 6,
            title: 'Code',
            description: '6-digit verification code'
        }
    },
    type: 'object',
    required: ['email', 'code'],
    title: 'ConfirmCodeRequest'
} as const;

export const ConfirmCodeResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['message', 'user_id'],
    title: 'ConfirmCodeResponse'
} as const;

export const CreateSessionRequestSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['project_id'],
    title: 'CreateSessionRequest',
    description: 'Request to create a new BA session'
} as const;

export const CreateSessionResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        current_phase: {
            type: 'string',
            title: 'Current Phase'
        }
    },
    type: 'object',
    required: ['session_id', 'status', 'current_phase'],
    title: 'CreateSessionResponse',
    description: 'Response with created session info'
} as const;

export const ForgotPasswordRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ForgotPasswordRequest'
} as const;

export const ForgotPasswordResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'expires_in'],
    title: 'ForgotPasswordResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        fullname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        login_provider: {
            type: 'boolean',
            title: 'Login Provider',
            description: 'false = credential login, true = OAuth provider login'
        }
    },
    type: 'object',
    required: ['email', 'login_provider'],
    title: 'LoginRequest'
} as const;

export const LoginResponseSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['user_id', 'access_token', 'refresh_token'],
    title: 'LoginResponse'
} as const;

export const LogoutResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'LogoutResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PhaseExecutionRequestSchema = {
    properties: {
        revision_feedback: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revision Feedback'
        }
    },
    type: 'object',
    title: 'PhaseExecutionRequest',
    description: 'Request to execute a phase (with optional revision feedback)'
} as const;

export const PhaseExecutionResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        phase: {
            type: 'string',
            title: 'Phase'
        },
        output: {
            type: 'string',
            title: 'Output'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['success', 'phase', 'output', 'message'],
    title: 'PhaseExecutionResponse',
    description: 'Response from phase execution'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductBriefResponseSchema = {
    properties: {
        product_summary: {
            type: 'string',
            title: 'Product Summary'
        },
        problem_statement: {
            type: 'string',
            title: 'Problem Statement'
        },
        target_users: {
            type: 'string',
            title: 'Target Users'
        },
        product_goals: {
            type: 'string',
            title: 'Product Goals'
        },
        scope: {
            type: 'string',
            title: 'Scope'
        },
        revision_count: {
            type: 'integer',
            title: 'Revision Count'
        }
    },
    type: 'object',
    required: ['product_summary', 'problem_statement', 'target_users', 'product_goals', 'scope', 'revision_count'],
    title: 'ProductBriefResponse',
    description: 'Response with PRD'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        is_private: {
            type: 'boolean',
            title: 'Is Private',
            default: true
        },
        tech_stack: {
            type: 'string',
            title: 'Tech Stack',
            default: 'nodejs-react'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProjectCreate',
    description: 'Schema for creating a new project. Code is auto-generated.'
} as const;

export const ProjectFlowMetricsSchema = {
    properties: {
        avg_cycle_time_hours: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Cycle Time Hours'
        },
        avg_lead_time_hours: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Lead Time Hours'
        },
        throughput_per_week: {
            type: 'number',
            title: 'Throughput Per Week'
        },
        total_completed: {
            type: 'integer',
            title: 'Total Completed'
        },
        work_in_progress: {
            type: 'integer',
            title: 'Work In Progress'
        },
        aging_items: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Aging Items'
        },
        bottlenecks: {
            additionalProperties: true,
            type: 'object',
            title: 'Bottlenecks'
        }
    },
    type: 'object',
    required: ['throughput_per_week', 'total_completed', 'work_in_progress', 'aging_items', 'bottlenecks'],
    title: 'ProjectFlowMetrics',
    description: 'Aggregated flow metrics for a project'
} as const;

export const ProjectPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        is_init: {
            type: 'boolean',
            title: 'Is Init'
        },
        is_private: {
            type: 'boolean',
            title: 'Is Private'
        },
        tech_stack: {
            type: 'string',
            title: 'Tech Stack'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'owner_id', 'is_init', 'is_private', 'tech_stack', 'created_at', 'updated_at'],
    title: 'ProjectPublic',
    description: 'Schema for project response with all fields from model.'
} as const;

export const ProjectRulesCreateSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        po_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Po Prompt'
        },
        dev_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dev Prompt'
        },
        tester_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tester Prompt'
        }
    },
    type: 'object',
    required: ['project_id'],
    title: 'ProjectRulesCreate'
} as const;

export const ProjectRulesPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        po_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Po Prompt'
        },
        dev_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dev Prompt'
        },
        tester_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tester Prompt'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'created_at', 'updated_at'],
    title: 'ProjectRulesPublic'
} as const;

export const ProjectRulesUpdateSchema = {
    properties: {
        po_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Po Prompt'
        },
        dev_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dev Prompt'
        },
        tester_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tester Prompt'
        }
    },
    type: 'object',
    title: 'ProjectRulesUpdate'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_init: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Init'
        },
        is_private: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Private'
        },
        tech_stack: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tech Stack'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        }
    },
    type: 'object',
    title: 'ProjectUpdate',
    description: 'Schema for updating a project. All fields are optional.'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic',
    description: 'Schema for list of projects response.'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest'
} as const;

export const RefreshTokenResponseSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['user_id', 'access_token', 'refresh_token'],
    title: 'RefreshTokenResponse'
} as const;

export const RegisterRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email',
            description: 'Email address'
        },
        fullname: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Fullname',
            description: 'Full name'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password',
            description: 'Password (min 8 chars, must contain letter and number)'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password',
            description: 'Password confirmation'
        }
    },
    type: 'object',
    required: ['email', 'fullname', 'password', 'confirm_password'],
    title: 'RegisterRequest'
} as const;

export const RegisterResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'email', 'expires_in'],
    title: 'RegisterResponse'
} as const;

export const RequirementsResponseSchema = {
    properties: {
        problem_goals: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Problem Goals'
        },
        users_stakeholders: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Users Stakeholders'
        },
        features_scope: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Features Scope'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['problem_goals', 'users_stakeholders', 'features_scope', 'total'],
    title: 'RequirementsResponse',
    description: 'Response with requirements list'
} as const;

export const ResendCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendCodeRequest'
} as const;

export const ResendCodeResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'email', 'expires_in'],
    title: 'ResendCodeResponse'
} as const;

export const ResetPasswordRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password', 'confirm_password'],
    title: 'ResetPasswordRequest'
} as const;

export const ResetPasswordResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ResetPasswordResponse'
} as const;

export const RoleSchema = {
    type: 'string',
    enum: ['admin', 'user'],
    title: 'Role'
} as const;

export const SendMessageRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'SendMessageRequest',
    description: 'Request to send a message in analysis phase'
} as const;

export const SendMessageResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        assistant_response: {
            type: 'string',
            title: 'Assistant Response'
        },
        extracted_requirements: {
            additionalProperties: true,
            type: 'object',
            title: 'Extracted Requirements'
        },
        turn_count: {
            type: 'integer',
            title: 'Turn Count'
        },
        total_requirements: {
            type: 'integer',
            title: 'Total Requirements'
        }
    },
    type: 'object',
    required: ['success', 'assistant_response', 'extracted_requirements', 'turn_count', 'total_requirements'],
    title: 'SendMessageResponse',
    description: 'Response with extracted requirements and assistant response'
} as const;

export const SessionStatusResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        current_phase: {
            type: 'string',
            title: 'Current Phase'
        },
        turn_count: {
            type: 'integer',
            title: 'Turn Count'
        },
        requirements_count: {
            type: 'integer',
            title: 'Requirements Count'
        },
        has_brief: {
            type: 'boolean',
            title: 'Has Brief'
        },
        flows_count: {
            type: 'integer',
            title: 'Flows Count'
        },
        epics_count: {
            type: 'integer',
            title: 'Epics Count'
        },
        stories_count: {
            type: 'integer',
            title: 'Stories Count'
        }
    },
    type: 'object',
    required: ['session_id', 'status', 'current_phase', 'turn_count', 'requirements_count', 'has_brief', 'flows_count', 'epics_count', 'stories_count'],
    title: 'SessionStatusResponse',
    description: 'Response with session status and progress'
} as const;

export const StoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StoriesPublic',
    description: 'List of stories response'
} as const;

export const StoryCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            '$ref': '#/components/schemas/StoryType',
            default: 'UserStory'
        },
        status: {
            '$ref': '#/components/schemas/StoryStatus',
            default: 'Todo'
        },
        epic_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epic Id'
        },
        acceptance_criteria: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acceptance Criteria'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        pause: {
            type: 'boolean',
            title: 'Pause',
            default: false
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        token_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Used'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['title', 'project_id'],
    title: 'StoryCreate',
    description: 'Schema for creating a new story (BA agent)'
} as const;

export const StoryFlowMetricsSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        review_started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Started At'
        },
        testing_started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Testing Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        cycle_time_hours: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cycle Time Hours'
        },
        lead_time_hours: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lead Time Hours'
        },
        age_in_current_status_hours: {
            type: 'number',
            title: 'Age In Current Status Hours'
        }
    },
    type: 'object',
    required: ['id', 'title', 'status', 'created_at', 'age_in_current_status_hours'],
    title: 'StoryFlowMetrics',
    description: 'Flow metrics for a single story'
} as const;

export const StoryPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            '$ref': '#/components/schemas/StoryType',
            default: 'UserStory'
        },
        status: {
            '$ref': '#/components/schemas/StoryStatus',
            default: 'Todo'
        },
        epic_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epic Id'
        },
        acceptance_criteria: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acceptance Criteria'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        pause: {
            type: 'boolean',
            title: 'Pause',
            default: false
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        token_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Used'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        parent: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/StorySimple'
                },
                {
                    type: 'null'
                }
            ]
        },
        children: {
            items: {
                '$ref': '#/components/schemas/StorySimple'
            },
            type: 'array',
            title: 'Children',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'id', 'project_id', 'created_at', 'updated_at'],
    title: 'StoryPublic',
    description: 'Full story schema with relationships for Kanban display'
} as const;

export const StorySimpleSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            '$ref': '#/components/schemas/StoryType',
            default: 'UserStory'
        },
        status: {
            '$ref': '#/components/schemas/StoryStatus',
            default: 'Todo'
        },
        epic_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epic Id'
        },
        acceptance_criteria: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acceptance Criteria'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        pause: {
            type: 'boolean',
            title: 'Pause',
            default: false
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        token_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Used'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'project_id', 'created_at', 'updated_at'],
    title: 'StorySimple',
    description: 'Simple story schema without nested relationships'
} as const;

export const StoryStatusSchema = {
    type: 'string',
    enum: ['Todo', 'InProgress', 'Review', 'Done'],
    title: 'StoryStatus'
} as const;

export const StoryTypeSchema = {
    type: 'string',
    enum: ['UserStory', 'EnablerStory'],
    title: 'StoryType'
} as const;

export const StoryUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/StoryType'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/StoryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        epic_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epic Id'
        },
        acceptance_criteria: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acceptance Criteria'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        pause: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pause'
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        token_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Used'
        }
    },
    type: 'object',
    title: 'StoryUpdate',
    description: 'Schema for updating story fields (BA/TL/Dev/Tester)'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['password', 'email'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/Role'
        }
    },
    type: 'object',
    required: ['id', 'email', 'role'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 3,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WIPLimitPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        column_name: {
            type: 'string',
            title: 'Column Name'
        },
        wip_limit: {
            type: 'integer',
            title: 'Wip Limit'
        },
        limit_type: {
            type: 'string',
            title: 'Limit Type'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'column_name', 'wip_limit', 'limit_type', 'created_at', 'updated_at'],
    title: 'WIPLimitPublic'
} as const;

export const WIPLimitUpdateSchema = {
    properties: {
        wip_limit: {
            type: 'integer',
            title: 'Wip Limit'
        },
        limit_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit Type'
        }
    },
    type: 'object',
    required: ['wip_limit'],
    title: 'WIPLimitUpdate'
} as const;

export const WIPLimitsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WIPLimitPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WIPLimitsPublic'
} as const;

export const WorkflowPoliciesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkflowPolicyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkflowPoliciesPublic'
} as const;

export const WorkflowPolicyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        from_status: {
            type: 'string',
            title: 'From Status'
        },
        to_status: {
            type: 'string',
            title: 'To Status'
        },
        criteria: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Criteria'
        },
        required_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Role'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'from_status', 'to_status', 'is_active', 'created_at', 'updated_at'],
    title: 'WorkflowPolicyPublic'
} as const;

export const WorkflowPolicyUpdateSchema = {
    properties: {
        criteria: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Criteria'
        },
        required_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Role'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'WorkflowPolicyUpdate'
} as const;