// This file is auto-generated by @hey-api/openapi-ts

export const AgentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        agent_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Type'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'AgentCreate'
} as const;

export const AgentExecutionRequestSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        user_input: {
            type: 'string',
            title: 'User Input'
        },
        agent_type: {
            type: 'string',
            title: 'Agent Type',
            default: 'po_agent'
        }
    },
    type: 'object',
    required: ['project_id', 'user_input'],
    title: 'AgentExecutionRequest'
} as const;

export const AgentExecutionResponseSchema = {
    properties: {
        execution_id: {
            type: 'string',
            title: 'Execution Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['execution_id', 'status', 'message'],
    title: 'AgentExecutionResponse'
} as const;

export const AgentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        agent_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'AgentPublic'
} as const;

export const AgentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        agent_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Type'
        }
    },
    type: 'object',
    title: 'AgentUpdate'
} as const;

export const AgentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentsPublic'
} as const;

export const AuthorTypeSchema = {
    type: 'string',
    enum: ['user', 'agent'],
    title: 'AuthorType'
} as const;

export const BacklogItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            type: 'string',
            title: 'Type',
            description: 'Type: Epic, Story, Task, Sub-task'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Status: Backlog, Todo, Doing, Done'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        pause: {
            type: 'boolean',
            title: 'Pause',
            default: false
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        sprint_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sprint Id'
        }
    },
    type: 'object',
    required: ['title', 'type', 'status', 'sprint_id'],
    title: 'BacklogItemCreate'
} as const;

export const BacklogItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            type: 'string',
            title: 'Type',
            description: 'Type: Epic, Story, Task, Sub-task'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Status: Backlog, Todo, Doing, Done'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        pause: {
            type: 'boolean',
            title: 'Pause',
            default: false
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sprint_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sprint Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'type', 'status', 'id', 'sprint_id', 'created_at', 'updated_at'],
    title: 'BacklogItemPublic'
} as const;

export const BacklogItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        estimate_value: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimate Value'
        },
        story_point: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Story Point'
        },
        pause: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pause'
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        sprint_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprint Id'
        }
    },
    type: 'object',
    title: 'BacklogItemUpdate'
} as const;

export const BacklogItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BacklogItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BacklogItemsPublic'
} as const;

export const ChatMessageCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        author_type: {
            '$ref': '#/components/schemas/AuthorType'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        agent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Id'
        }
    },
    type: 'object',
    required: ['content', 'author_type', 'project_id'],
    title: 'ChatMessageCreate'
} as const;

export const ChatMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        author_type: {
            '$ref': '#/components/schemas/AuthorType'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        agent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'author_type', 'content', 'created_at', 'updated_at'],
    title: 'ChatMessagePublic'
} as const;

export const ChatMessageUpdateSchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    title: 'ChatMessageUpdate'
} as const;

export const ChatMessagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatMessagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatMessagesPublic'
} as const;

export const ConfirmCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        code: {
            type: 'string',
            maxLength: 6,
            minLength: 6,
            title: 'Code',
            description: '6-digit verification code'
        }
    },
    type: 'object',
    required: ['email', 'code'],
    title: 'ConfirmCodeRequest'
} as const;

export const ConfirmCodeResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['message', 'user_id'],
    title: 'ConfirmCodeResponse'
} as const;

export const ForgotPasswordRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ForgotPasswordRequest'
} as const;

export const ForgotPasswordResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'expires_in'],
    title: 'ForgotPasswordResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        fullname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        login_provider: {
            type: 'boolean',
            title: 'Login Provider',
            description: 'false = credential login, true = OAuth provider login'
        }
    },
    type: 'object',
    required: ['email', 'login_provider'],
    title: 'LoginRequest'
} as const;

export const LoginResponseSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['user_id', 'access_token', 'refresh_token'],
    title: 'LoginResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        is_init: {
            type: 'boolean',
            title: 'Is Init',
            default: false
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['code', 'name', 'owner_id'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        is_init: {
            type: 'boolean',
            title: 'Is Init',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['code', 'name', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_init: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Init'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest'
} as const;

export const RefreshTokenResponseSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['user_id', 'access_token', 'refresh_token'],
    title: 'RefreshTokenResponse'
} as const;

export const RegisterRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email',
            description: 'Email address'
        },
        fullname: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Fullname',
            description: 'Full name'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password',
            description: 'Password (min 8 chars, must contain letter and number)'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password',
            description: 'Password confirmation'
        }
    },
    type: 'object',
    required: ['email', 'fullname', 'password', 'confirm_password'],
    title: 'RegisterRequest'
} as const;

export const RegisterResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'email', 'expires_in'],
    title: 'RegisterResponse'
} as const;

export const ResendCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendCodeRequest'
} as const;

export const ResendCodeResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['message', 'email', 'expires_in'],
    title: 'ResendCodeResponse'
} as const;

export const ResetPasswordRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password', 'confirm_password'],
    title: 'ResetPasswordRequest'
} as const;

export const ResetPasswordResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ResetPasswordResponse'
} as const;

export const RoleSchema = {
    type: 'string',
    enum: ['admin', 'user'],
    title: 'Role'
} as const;

export const SprintCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        number: {
            type: 'integer',
            minimum: 1,
            title: 'Number',
            description: 'Sprint number (1, 2, 3...)'
        },
        goal: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Goal'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Status: Planning, Active, Completed, Cancelled'
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date'
        },
        velocity_plan: {
            type: 'string',
            title: 'Velocity Plan',
            description: 'Planned velocity',
            default: '0'
        },
        velocity_actual: {
            type: 'string',
            title: 'Velocity Actual',
            description: 'Actual velocity',
            default: '0'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['name', 'number', 'goal', 'status', 'start_date', 'end_date', 'project_id'],
    title: 'SprintCreate'
} as const;

export const SprintPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        number: {
            type: 'integer',
            minimum: 1,
            title: 'Number',
            description: 'Sprint number (1, 2, 3...)'
        },
        goal: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Goal'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Status: Planning, Active, Completed, Cancelled'
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date'
        },
        velocity_plan: {
            type: 'string',
            title: 'Velocity Plan',
            description: 'Planned velocity',
            default: '0'
        },
        velocity_actual: {
            type: 'string',
            title: 'Velocity Actual',
            description: 'Actual velocity',
            default: '0'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'number', 'goal', 'status', 'start_date', 'end_date', 'id', 'project_id', 'created_at', 'updated_at'],
    title: 'SprintPublic'
} as const;

export const SprintUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        number: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        velocity_plan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Velocity Plan'
        },
        velocity_actual: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Velocity Actual'
        }
    },
    type: 'object',
    title: 'SprintUpdate'
} as const;

export const SprintsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SprintPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SprintsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['username', 'password', 'email'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/Role'
        }
    },
    type: 'object',
    required: ['id', 'username', 'email', 'role'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 3,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;