// This file is auto-generated by @hey-api/openapi-ts

export type AgentCreate = {
    name: string;
    agent_type?: (string | null);
};

export type AgentExecutionRequest = {
    project_id: string;
    user_input: string;
    agent_type?: string;
};

export type AgentExecutionResponse = {
    execution_id: string;
    status: string;
    message: string;
};

export type AgentPublic = {
    name: string;
    agent_type?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type AgentsPublic = {
    data: Array<AgentPublic>;
    count: number;
};

export type AgentUpdate = {
    name?: (string | null);
    agent_type?: (string | null);
};

export type AuthorType = 'user' | 'agent';

export type BacklogItemCreate = {
    title: string;
    description?: (string | null);
    /**
     * Type: Epic, Story, Task, Sub-task
     */
    type: string;
    /**
     * Status: Backlog, Todo, Doing, Done
     */
    status: string;
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: boolean;
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    sprint_id: string;
};

export type BacklogItemPublic = {
    title: string;
    description?: (string | null);
    /**
     * Type: Epic, Story, Task, Sub-task
     */
    type: string;
    /**
     * Status: Backlog, Todo, Doing, Done
     */
    status: string;
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: boolean;
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    id: string;
    sprint_id: string;
    created_at: string;
    updated_at: string;
};

export type BacklogItemsPublic = {
    data: Array<BacklogItemPublic>;
    count: number;
};

export type BacklogItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    type?: (string | null);
    status?: (string | null);
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: (boolean | null);
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    sprint_id?: (string | null);
};

export type ChatMessageCreate = {
    content: string;
    author_type: AuthorType;
    project_id: string;
    agent_id?: (string | null);
};

export type ChatMessagePublic = {
    id: string;
    project_id: string;
    author_type: AuthorType;
    user_id?: (string | null);
    agent_id?: (string | null);
    content: string;
    created_at: string;
    updated_at: string;
};

export type ChatMessagesPublic = {
    data: Array<ChatMessagePublic>;
    count: number;
};

export type ChatMessageUpdate = {
    content?: (string | null);
};

export type ConfirmCodeRequest = {
    email: string;
    /**
     * 6-digit verification code
     */
    code: string;
};

export type ConfirmCodeResponse = {
    message: string;
    user_id: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ForgotPasswordResponse = {
    message: string;
    expires_in: number;
};

export type GitHubRepositoriesPublic = {
    data: Array<GitHubRepository>;
    count: number;
};

export type GitHubRepository = {
    id: number;
    name: string;
    full_name: string;
    url: string;
    description?: (string | null);
    private: boolean;
    owner: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password?: (string | null);
    fullname?: (string | null);
    /**
     * false = credential login, true = OAuth provider login
     */
    login_provider: boolean;
};

export type LoginResponse = {
    user_id: string;
    access_token: string;
    refresh_token: string;
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    code: string;
    name: string;
    is_init?: boolean;
    owner_id: string;
};

export type ProjectGitHubLink = {
    github_repository_id: number;
    github_repository_name: string;
    github_installation_id: string;
};

export type ProjectPublic = {
    code: string;
    name: string;
    is_init?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    code?: (string | null);
    name?: (string | null);
    is_init?: (boolean | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RefreshTokenResponse = {
    user_id: string;
    access_token: string;
    refresh_token: string;
};

export type RegisterRequest = {
    /**
     * Email address
     */
    email: string;
    /**
     * Full name
     */
    fullname: string;
    /**
     * Password (min 8 chars, must contain letter and number)
     */
    password: string;
    /**
     * Password confirmation
     */
    confirm_password: string;
};

export type RegisterResponse = {
    message: string;
    email: string;
    expires_in: number;
};

export type ResendCodeRequest = {
    email: string;
};

export type ResendCodeResponse = {
    message: string;
    email: string;
    expires_in: number;
};

export type ResetPasswordRequest = {
    token: string;
    new_password: string;
    confirm_password: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type Role = 'admin' | 'user';

export type SprintCreate = {
    name: string;
    /**
     * Sprint number (1, 2, 3...)
     */
    number: number;
    goal: string;
    /**
     * Status: Planning, Active, Completed, Cancelled
     */
    status: string;
    start_date: string;
    end_date: string;
    /**
     * Planned velocity
     */
    velocity_plan?: string;
    /**
     * Actual velocity
     */
    velocity_actual?: string;
    project_id: string;
};

export type SprintPublic = {
    name: string;
    /**
     * Sprint number (1, 2, 3...)
     */
    number: number;
    goal: string;
    /**
     * Status: Planning, Active, Completed, Cancelled
     */
    status: string;
    start_date: string;
    end_date: string;
    /**
     * Planned velocity
     */
    velocity_plan?: string;
    /**
     * Actual velocity
     */
    velocity_actual?: string;
    id: string;
    project_id: string;
    created_at: string;
    updated_at: string;
};

export type SprintsPublic = {
    data: Array<SprintPublic>;
    count: number;
};

export type SprintUpdate = {
    name?: (string | null);
    number?: (number | null);
    goal?: (string | null);
    status?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    velocity_plan?: (string | null);
    velocity_actual?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    password: string;
    email: string;
};

export type UserPublic = {
    id: string;
    full_name: string;
    email: string;
    role: Role;
};

export type UserRegister = {
    username: string;
    email: string;
    password: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    email?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    username?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentExecutionExecuteAgentData = {
    requestBody: AgentExecutionRequest;
};

export type AgentExecutionExecuteAgentResponse = (AgentExecutionResponse);

export type AgentExecutionExecuteAgentSyncData = {
    requestBody: AgentExecutionRequest;
};

export type AgentExecutionExecuteAgentSyncResponse = ({
    [key: string]: unknown;
});

export type AgentsListAgentsData = {
    agentType?: (string | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
};

export type AgentsListAgentsResponse = (AgentsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentCreate;
};

export type AgentsCreateAgentResponse = (AgentPublic);

export type AgentsGetAgentData = {
    agentId: string;
};

export type AgentsGetAgentResponse = (AgentPublic);

export type AgentsUpdateAgentData = {
    agentId: string;
    requestBody: AgentUpdate;
};

export type AgentsUpdateAgentResponse = (AgentPublic);

export type AgentsDeleteAgentData = {
    agentId: string;
};

export type AgentsDeleteAgentResponse = (void);

export type AuthenticationLoginData = {
    requestBody: LoginRequest;
};

export type AuthenticationLoginResponse = (LoginResponse);

export type AuthenticationRegisterData = {
    requestBody: RegisterRequest;
};

export type AuthenticationRegisterResponse = (RegisterResponse);

export type AuthenticationConfirmCodeData = {
    requestBody: ConfirmCodeRequest;
};

export type AuthenticationConfirmCodeResponse = (ConfirmCodeResponse);

export type AuthenticationResendCodeData = {
    requestBody: ResendCodeRequest;
};

export type AuthenticationResendCodeResponse = (ResendCodeResponse);

export type AuthenticationRefreshTokenData = {
    refreshToken?: string;
    requestBody: RefreshTokenRequest;
};

export type AuthenticationRefreshTokenResponse = (RefreshTokenResponse);

export type AuthenticationForgotPasswordData = {
    requestBody: ForgotPasswordRequest;
};

export type AuthenticationForgotPasswordResponse = (ForgotPasswordResponse);

export type AuthenticationResetPasswordData = {
    requestBody: ResetPasswordRequest;
};

export type AuthenticationResetPasswordResponse = (ResetPasswordResponse);

export type BacklogItemsGetBacklogItemsData = {
    assigneeId?: (string | null);
    limit?: number;
    skip?: number;
    sprintId?: (string | null);
    status?: (string | null);
    type?: (string | null);
};

export type BacklogItemsGetBacklogItemsResponse = (BacklogItemsPublic);

export type BacklogItemsCreateBacklogItemData = {
    requestBody: BacklogItemCreate;
};

export type BacklogItemsCreateBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsGetBacklogItemData = {
    itemId: string;
};

export type BacklogItemsGetBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsUpdateBacklogItemData = {
    itemId: string;
    requestBody: BacklogItemUpdate;
};

export type BacklogItemsUpdateBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsDeleteBacklogItemData = {
    itemId: string;
};

export type BacklogItemsDeleteBacklogItemResponse = ({
    [key: string]: unknown;
});

export type BacklogItemsMoveBacklogItemData = {
    itemId: string;
    /**
     * Vị trí mới trong cột
     */
    newRank: number;
    /**
     * Sprint đích (nếu di chuyển sang sprint khác)
     */
    newSprintId?: (string | null);
    /**
     * Cột đích (Backlog, Todo, Doing, Done)
     */
    newStatus: string;
};

export type BacklogItemsMoveBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsGetKanbanBoardData = {
    sprintId: string;
};

export type BacklogItemsGetKanbanBoardResponse = (unknown);

export type ChatGetWebsocketInfoResponse = (unknown);

export type ChatGetConnectionStatsResponse = (unknown);

export type GithubGithubWebhookResponse = ({
    [key: string]: unknown;
});

export type GithubGithubCallbackData = {
    installationId: number;
    setupAction?: (string | null);
};

export type GithubGithubCallbackResponse = (unknown);

export type GithubLinkInstallationToUserData = {
    installationId: number;
};

export type GithubLinkInstallationToUserResponse = ({
    [key: string]: unknown;
});

export type GithubListGithubRepositoriesData = {
    installationId?: (string | null);
    limit?: number;
    skip?: number;
};

export type GithubListGithubRepositoriesResponse = (GitHubRepositoriesPublic);

export type GithubLinkGithubRepositoryData = {
    projectId: string;
    requestBody: ProjectGitHubLink;
};

export type GithubLinkGithubRepositoryResponse = (ProjectPublic);

export type GithubUnlinkGithubRepositoryData = {
    projectId: string;
};

export type GithubUnlinkGithubRepositoryResponse = (ProjectPublic);

export type GithubListGithubInstallationsData = {
    limit?: number;
    skip?: number;
};

export type GithubListGithubInstallationsResponse = ({
    [key: string]: unknown;
});

export type MessagesListMessagesData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type MessagesListMessagesResponse = (ChatMessagesPublic);

export type MessagesCreateMessageData = {
    requestBody: ChatMessageCreate;
};

export type MessagesCreateMessageResponse = (ChatMessagePublic);

export type MessagesUpdateMessageData = {
    messageId: string;
    requestBody: ChatMessageUpdate;
};

export type MessagesUpdateMessageResponse = (ChatMessagePublic);

export type MessagesDeleteMessageData = {
    messageId: string;
};

export type MessagesDeleteMessageResponse = (void);

export type MessagesDeleteAllMessagesByProjectData = {
    projectId: string;
};

export type MessagesDeleteAllMessagesByProjectResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    /**
     * Tìm theo code
     */
    code?: (string | null);
    limit?: number;
    /**
     * Tìm theo name
     */
    name?: (string | null);
    ownerId?: (string | null);
    skip?: number;
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type SprintsListSprintsData = {
    limit?: number;
    /**
     * Search by name
     */
    name?: (string | null);
    /**
     * Filter by project
     */
    projectId?: (string | null);
    skip?: number;
    /**
     * Filter by status
     */
    status?: (string | null);
};

export type SprintsListSprintsResponse = (SprintsPublic);

export type SprintsCreateSprintData = {
    requestBody: SprintCreate;
};

export type SprintsCreateSprintResponse = (SprintPublic);

export type SprintsGetSprintData = {
    sprintId: string;
};

export type SprintsGetSprintResponse = (SprintPublic);

export type SprintsUpdateSprintData = {
    requestBody: SprintUpdate;
    sprintId: string;
};

export type SprintsUpdateSprintResponse = (SprintPublic);

export type SprintsDeleteSprintData = {
    sprintId: string;
};

export type SprintsDeleteSprintResponse = (void);

export type SprintsGetActiveSprintData = {
    projectId: string;
};

export type SprintsGetActiveSprintResponse = (SprintPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);