// This file is auto-generated by @hey-api/openapi-ts

export type AgentCreate = {
    project_id: string;
    role_type: string;
    human_name?: (string | null);
};

export type AgentPublic = {
    id: string;
    project_id: string;
    name: string;
    human_name: string;
    role_type: string;
    agent_type?: (string | null);
    status: AgentStatus;
    created_at: string;
    updated_at: string;
};

export type AgentsPublic = {
    data: Array<AgentPublic>;
    count: number;
};

/**
 * Runtime status of an agent (unified for runtime and database)
 */
export type AgentStatus = 'created' | 'starting' | 'running' | 'idle' | 'busy' | 'stopping' | 'stopped' | 'error' | 'terminated';

export type AgentUpdate = {
    human_name?: (string | null);
    status?: (AgentStatus | null);
};

export type AuthorType = 'user' | 'agent';

export type Body_authentication_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessageCreate = {
    content: string;
    author_type: AuthorType;
    project_id: string;
    agent_id?: (string | null);
    message_type?: (string | null);
    structured_data?: ({
    [key: string]: unknown;
} | null);
};

export type ChatMessagePublic = {
    id: string;
    project_id: string;
    author_type: AuthorType;
    user_id?: (string | null);
    agent_id?: (string | null);
    content: string;
    message_type?: (string | null);
    structured_data?: (unknown | null);
    message_metadata?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
    updated_at: string;
};

export type ChatMessagesPublic = {
    data: Array<ChatMessagePublic>;
    count: number;
};

export type ChatMessageUpdate = {
    content?: (string | null);
};

export type ConfirmCodeRequest = {
    email: string;
    code: string;
};

export type ConfirmCodeResponse = {
    message: string;
};

/**
 * Request to create agent pool.
 */
export type CreatePoolRequest = {
    /**
     * Role type: team_leader, business_analyst, developer, tester
     */
    role_type: string;
    config?: PoolConfigSchema;
};

/**
 * Response containing file content
 */
export type FileContentResponse = {
    path: string;
    content: string;
    encoding?: string;
    size: number;
};

/**
 * Single file or folder node
 */
export type FileNode = {
    name: string;
    type: string;
    path: string;
    size?: (number | null);
    modified?: (string | null);
    children?: (Array<FileNode> | null);
};

/**
 * Response containing the file tree
 */
export type FileTreeResponse = {
    project_id: string;
    root: FileNode;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ForgotPasswordResponse = {
    message: string;
    email: string;
};

/**
 * Response containing git status of files
 */
export type GitStatusResponse = {
    project_id: string;
    branch: string;
    modified: Array<string>;
    untracked: Array<string>;
    staged: Array<string>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password?: (string | null);
    fullname?: (string | null);
    login_provider?: boolean;
};

export type LoginResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

export type LogoutResponse = {
    message: string;
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Pool configuration schema.
 */
export type PoolConfigSchema = {
    max_agents?: number;
};

/**
 * Pool information response.
 */
export type PoolResponse = {
    pool_name: string;
    role_type: string;
    active_agents: number;
    max_agents: number;
    total_spawned: number;
    total_terminated: number;
    is_running: boolean;
    agents: Array<{
        [key: string]: unknown;
    }>;
};

export type ProjectCreate = {
    name: string;
    description?: (string | null);
    repository_url?: (string | null);
    tech_stack?: (Array<string> | null);
};

/**
 * Aggregated flow metrics for a project
 */
export type ProjectFlowMetrics = {
    avg_cycle_time_hours?: (number | null);
    avg_lead_time_hours?: (number | null);
    throughput_per_week: number;
    total_completed: number;
    work_in_progress: number;
    aging_items: Array<{
        [key: string]: unknown;
    }>;
    bottlenecks: {
        [key: string]: unknown;
    };
};

export type ProjectPublic = {
    id: string;
    code: string;
    name: string;
    description?: (string | null);
    repository_url?: (string | null);
    tech_stack?: (Array<string> | null);
    owner_id: string;
    is_init: boolean;
    created_at: string;
    updated_at: string;
};

export type ProjectRulesCreate = {
    project_id: string;
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
};

export type ProjectRulesPublic = {
    id: string;
    project_id: string;
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProjectRulesUpdate = {
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    repository_url?: (string | null);
    tech_stack?: (Array<string> | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RefreshTokenResponse = {
    access_token: string;
    token_type?: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    confirm_password: string;
    full_name?: (string | null);
};

export type RegisterResponse = {
    message: string;
    email: string;
};

export type ResendCodeRequest = {
    email: string;
};

export type ResendCodeResponse = {
    message: string;
    email: string;
};

export type ResetPasswordRequest = {
    token: string;
    new_password: string;
    confirm_password: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type Role = 'admin' | 'user';

/**
 * Request to spawn agent.
 */
export type SpawnAgentRequest = {
    /**
     * Project ID to assign agent to
     */
    project_id: string;
    /**
     * Pool name
     */
    pool_name: string;
    /**
     * Agent role type
     */
    role_type: string;
    /**
     * Optional human-friendly name
     */
    human_name?: (string | null);
};

export type StoriesPublic = {
    data: Array<{
        [key: string]: unknown;
    }>;
    count: number;
};

/**
 * Schema for creating a new story.
 */
export type StoryCreate = {
    title: string;
    description?: (string | null);
    story_type?: StoryType;
    priority?: number;
    estimated_hours?: (number | null);
    actual_hours?: (number | null);
    assigned_to?: (string | null);
    sprint_id?: (string | null);
    epic_id?: (string | null);
    parent_story_id?: (string | null);
    tags?: (Array<string> | null);
    acceptance_criteria?: (string | null);
    business_value?: (number | null);
    risk_level?: ('low' | 'medium' | 'high' | 'critical' | null);
    target_release?: (string | null);
    dependencies?: (Array<string> | null);
    blocked_by?: (string | null);
    blocking?: (Array<string> | null);
    attachments?: (Array<string> | null);
    labels?: (Array<string> | null);
    project_id: string;
};

/**
 * Flow metrics for a single story
 */
export type StoryFlowMetrics = {
    id: string;
    title: string;
    status: string;
    created_at: string;
    cycle_time_hours?: (number | null);
    lead_time_hours?: (number | null);
    age_in_current_status_hours: number;
    age_in_current_status_days: number;
    blocked?: boolean;
    blocker_count?: number;
};

/**
 * Schema for story response.
 */
export type StoryPublic = {
    title: string;
    description?: (string | null);
    story_type?: StoryType;
    priority?: number;
    estimated_hours?: (number | null);
    actual_hours?: (number | null);
    assigned_to?: (string | null);
    sprint_id?: (string | null);
    epic_id?: (string | null);
    parent_story_id?: (string | null);
    tags?: (Array<string> | null);
    acceptance_criteria?: (string | null);
    business_value?: (number | null);
    risk_level?: ('low' | 'medium' | 'high' | 'critical' | null);
    target_release?: (string | null);
    dependencies?: (Array<string> | null);
    blocked_by?: (string | null);
    blocking?: (Array<string> | null);
    attachments?: (Array<string> | null);
    labels?: (Array<string> | null);
    id: string;
    project_id: string;
    status: StoryStatus;
    created_at: string;
    updated_at: string;
    completed_at?: (string | null);
};

export type StoryStatus = 'Todo' | 'InProgress' | 'Review' | 'Done' | 'Archived';

export type StoryType = 'UserStory' | 'EnablerStory';

export type StoryUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (StoryStatus | null);
    story_type?: (StoryType | null);
    priority?: (number | null);
    estimated_hours?: (number | null);
    actual_hours?: (number | null);
    assigned_to?: (string | null);
    sprint_id?: (string | null);
    epic_id?: (string | null);
    parent_story_id?: (string | null);
    tags?: (Array<string> | null);
    acceptance_criteria?: (string | null);
    business_value?: (number | null);
    risk_level?: ('low' | 'medium' | 'high' | 'critical' | null);
    target_release?: (string | null);
    dependencies?: (Array<string> | null);
    blocked_by?: (string | null);
    blocking?: (Array<string> | null);
    attachments?: (Array<string> | null);
    labels?: (Array<string> | null);
};

/**
 * System statistics response.
 */
export type SystemStatsResponse = {
    uptime_seconds: number;
    total_pools: number;
    total_agents: number;
    pools: Array<PoolResponse>;
};

/**
 * Request to terminate agent.
 */
export type TerminateAgentRequest = {
    /**
     * Pool name
     */
    pool_name: string;
    /**
     * Agent ID to terminate
     */
    agent_id: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username?: (string | null);
    password: string;
    email: string;
};

export type UserPublic = {
    id: string;
    full_name?: (string | null);
    email: string;
    role: Role;
};

export type UserRegister = {
    username: string;
    email: string;
    password: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    email?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    username?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WIPLimitPublic = {
    id: string;
    project_id: string;
    column_name: string;
    wip_limit: number;
    limit_type: string;
    created_at: string;
    updated_at: string;
};

export type WIPLimitsPublic = {
    data: Array<WIPLimitPublic>;
    count: number;
};

export type WIPLimitUpdate = {
    wip_limit: number;
    limit_type?: (string | null);
};

export type WorkflowPoliciesPublic = {
    data: Array<WorkflowPolicyPublic>;
    count: number;
};

export type WorkflowPolicyPublic = {
    id: string;
    project_id: string;
    from_status: string;
    to_status: string;
    criteria?: ({
    [key: string]: unknown;
} | null);
    is_active: boolean;
    definition_of_ready?: (Array<string> | null);
    definition_of_done?: (Array<string> | null);
    created_at: string;
    updated_at: string;
};

export type WorkflowPolicyUpdate = {
    criteria?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
    definition_of_ready?: (Array<string> | null);
    definition_of_done?: (Array<string> | null);
};

export type AgentManagementListPoolsResponse = (Array<PoolResponse>);

export type AgentManagementCreatePoolData = {
    requestBody: CreatePoolRequest;
};

export type AgentManagementCreatePoolResponse = (PoolResponse);

export type AgentManagementGetPoolStatsData = {
    poolName: string;
};

export type AgentManagementGetPoolStatsResponse = (PoolResponse);

export type AgentManagementDeletePoolData = {
    graceful?: boolean;
    poolName: string;
};

export type AgentManagementDeletePoolResponse = (unknown);

export type AgentManagementSpawnAgentData = {
    requestBody: SpawnAgentRequest;
};

export type AgentManagementSpawnAgentResponse = (unknown);

export type AgentManagementTerminateAgentData = {
    requestBody: TerminateAgentRequest;
};

export type AgentManagementTerminateAgentResponse = (unknown);

export type AgentManagementGetSystemStatsResponse = (SystemStatsResponse);

export type AgentManagementGetDashboardDataResponse = (unknown);

export type AgentManagementGetAlertsData = {
    limit?: number;
};

export type AgentManagementGetAlertsResponse = (unknown);

export type AgentManagementGetMetricsTimeseriesData = {
    /**
     * Data point interval: auto, 5m, 15m, 1h, 1d
     */
    interval?: string;
    /**
     * Metric type: utilization, executions, tokens, success_rate
     */
    metricType: string;
    /**
     * Filter by pool name
     */
    poolName?: (string | null);
    /**
     * Time range: 1h, 6h, 24h, 7d, 30d
     */
    timeRange?: string;
};

export type AgentManagementGetMetricsTimeseriesResponse = (unknown);

export type AgentManagementGetMetricsAggregatedData = {
    /**
     * Group by: pool, hour, day
     */
    groupBy?: string;
    /**
     * Time range: 1h, 6h, 24h, 7d, 30d
     */
    timeRange?: string;
};

export type AgentManagementGetMetricsAggregatedResponse = (unknown);

export type AgentManagementGetTokenMetricsData = {
    /**
     * Group by: pool, agent_type
     */
    groupBy?: string;
    /**
     * Time range: 1h, 6h, 24h, 7d, 30d
     */
    timeRange?: string;
};

export type AgentManagementGetTokenMetricsResponse = (unknown);

export type AgentManagementGetAllAgentHealthResponse = (unknown);

export type AgentManagementGetExecutionsData = {
    /**
     * Filter by agent type
     */
    agentType?: (string | null);
    limit?: number;
    /**
     * Filter by project ID
     */
    projectId?: (string | null);
    /**
     * Filter by status: pending, running, completed, failed, cancelled
     */
    status?: (string | null);
};

export type AgentManagementGetExecutionsResponse = (unknown);

export type AgentManagementGetExecutionStatsData = {
    projectId?: (string | null);
};

export type AgentManagementGetExecutionStatsResponse = (unknown);

export type AgentManagementGetExecutionDetailData = {
    executionId: string;
};

export type AgentManagementGetExecutionDetailResponse = (unknown);

export type AgentsGetProjectAgentsData = {
    projectId: string;
};

export type AgentsGetProjectAgentsResponse = (AgentsPublic);

export type AgentsListAgentsData = {
    agentType?: (string | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
};

export type AgentsListAgentsResponse = (AgentsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentCreate;
};

export type AgentsCreateAgentResponse = (AgentPublic);

export type AgentsGetAgentData = {
    agentId: string;
};

export type AgentsGetAgentResponse = (AgentPublic);

export type AgentsUpdateAgentData = {
    agentId: string;
    requestBody: AgentUpdate;
};

export type AgentsUpdateAgentResponse = (AgentPublic);

export type AgentsDeleteAgentData = {
    agentId: string;
};

export type AgentsDeleteAgentResponse = (void);

export type AuthenticationLoginAccessTokenData = {
    formData: Body_authentication_login_access_token;
};

export type AuthenticationLoginAccessTokenResponse = (LoginResponse);

export type AuthenticationLoginData = {
    requestBody: LoginRequest;
};

export type AuthenticationLoginResponse = (LoginResponse);

export type AuthenticationRegisterData = {
    requestBody: RegisterRequest;
};

export type AuthenticationRegisterResponse = (RegisterResponse);

export type AuthenticationConfirmCodeData = {
    requestBody: ConfirmCodeRequest;
};

export type AuthenticationConfirmCodeResponse = (ConfirmCodeResponse);

export type AuthenticationResendCodeData = {
    requestBody: ResendCodeRequest;
};

export type AuthenticationResendCodeResponse = (ResendCodeResponse);

export type AuthenticationRefreshTokenData = {
    refreshToken?: string;
    requestBody: RefreshTokenRequest;
};

export type AuthenticationRefreshTokenResponse = (RefreshTokenResponse);

export type AuthenticationForgotPasswordData = {
    requestBody: ForgotPasswordRequest;
};

export type AuthenticationForgotPasswordResponse = (ForgotPasswordResponse);

export type AuthenticationResetPasswordData = {
    requestBody: ResetPasswordRequest;
};

export type AuthenticationResetPasswordResponse = (ResetPasswordResponse);

export type AuthenticationLogoutResponse = (LogoutResponse);

export type ChatChatHealthResponse = (unknown);

export type FilesListProjectFilesData = {
    /**
     * Maximum depth to traverse
     */
    depth?: number;
    projectId: string;
};

export type FilesListProjectFilesResponse = (FileTreeResponse);

export type FilesGetFileContentData = {
    /**
     * Relative path to the file
     */
    path: string;
    projectId: string;
};

export type FilesGetFileContentResponse = (FileContentResponse);

export type FilesGetGitStatusData = {
    projectId: string;
};

export type FilesGetGitStatusResponse = (GitStatusResponse);

export type LeanKanbanGetWipLimitsData = {
    projectId: string;
};

export type LeanKanbanGetWipLimitsResponse = (WIPLimitsPublic);

export type LeanKanbanUpdateWipLimitData = {
    columnName: string;
    projectId: string;
    requestBody: WIPLimitUpdate;
};

export type LeanKanbanUpdateWipLimitResponse = (WIPLimitPublic);

export type LeanKanbanValidateWipBeforeMoveData = {
    projectId: string;
    storyId: string;
    targetStatus: string;
};

export type LeanKanbanValidateWipBeforeMoveResponse = ({
    [key: string]: unknown;
});

export type LeanKanbanInitializeDefaultPoliciesData = {
    projectId: string;
};

export type LeanKanbanInitializeDefaultPoliciesResponse = ({
    [key: string]: unknown;
});

export type LeanKanbanGetWorkflowPoliciesData = {
    projectId: string;
};

export type LeanKanbanGetWorkflowPoliciesResponse = (WorkflowPoliciesPublic);

export type LeanKanbanUpdateWorkflowPolicyData = {
    fromStatus: string;
    projectId: string;
    requestBody: WorkflowPolicyUpdate;
    toStatus: string;
};

export type LeanKanbanUpdateWorkflowPolicyResponse = (WorkflowPolicyPublic);

export type LeanKanbanValidatePolicyBeforeMoveData = {
    fromStatus: string;
    projectId: string;
    storyId: string;
    toStatus: string;
};

export type LeanKanbanValidatePolicyBeforeMoveResponse = ({
    [key: string]: unknown;
});

export type LeanKanbanGetProjectFlowMetricsData = {
    days?: number;
    projectId: string;
};

export type LeanKanbanGetProjectFlowMetricsResponse = (ProjectFlowMetrics);

export type LeanKanbanGetStoryFlowMetricsData = {
    storyId: string;
};

export type LeanKanbanGetStoryFlowMetricsResponse = (StoryFlowMetrics);

export type MessagesListMessagesData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type MessagesListMessagesResponse = (ChatMessagesPublic);

export type MessagesCreateMessageData = {
    requestBody: ChatMessageCreate;
};

export type MessagesCreateMessageResponse = (ChatMessagePublic);

export type MessagesUpdateMessageData = {
    messageId: string;
    requestBody: ChatMessageUpdate;
};

export type MessagesUpdateMessageResponse = (ChatMessagePublic);

export type MessagesDeleteMessageData = {
    messageId: string;
};

export type MessagesDeleteMessageResponse = (void);

export type MessagesDeleteAllMessagesByProjectData = {
    projectId: string;
};

export type MessagesDeleteAllMessagesByProjectResponse = (Message);

export type OauthGoogleLoginResponse = (unknown);

export type OauthGithubLoginResponse = (unknown);

export type OauthFacebookLoginResponse = (unknown);

export type OauthOauthCallbackData = {
    code: string;
    state: string;
};

export type OauthOauthCallbackResponse = (unknown);

export type ProjectRulesCreateProjectRulesData = {
    requestBody: ProjectRulesCreate;
};

export type ProjectRulesCreateProjectRulesResponse = (ProjectRulesPublic);

export type ProjectRulesGetProjectRulesData = {
    projectId: string;
};

export type ProjectRulesGetProjectRulesResponse = (ProjectRulesPublic);

export type ProjectRulesUpdateProjectRulesData = {
    projectId: string;
    requestBody: ProjectRulesUpdate;
};

export type ProjectRulesUpdateProjectRulesResponse = (ProjectRulesPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type StoriesCreateStoryData = {
    requestBody: StoryCreate;
};

export type StoriesCreateStoryResponse = (StoryPublic);

export type StoriesListStoriesData = {
    assigneeId?: (string | null);
    limit?: number;
    projectId?: (string | null);
    skip?: number;
    status?: (StoryStatus | null);
    type?: (StoryType | null);
};

export type StoriesListStoriesResponse = (StoriesPublic);

export type StoriesGetKanbanBoardData = {
    projectId: string;
};

export type StoriesGetKanbanBoardResponse = (unknown);

export type StoriesAssignStoryData = {
    assigneeId: string;
    reviewerId?: (string | null);
    storyId: string;
};

export type StoriesAssignStoryResponse = (StoryPublic);

export type StoriesUpdateStoryStatusData = {
    newStatus: StoryStatus;
    storyId: string;
};

export type StoriesUpdateStoryStatusResponse = (StoryPublic);

export type StoriesGetStoryData = {
    storyId: string;
};

export type StoriesGetStoryResponse = (StoryPublic);

export type StoriesUpdateStoryData = {
    requestBody: StoryUpdate;
    storyId: string;
};

export type StoriesUpdateStoryResponse = (StoryPublic);

export type StoriesDeleteStoryData = {
    storyId: string;
};

export type StoriesDeleteStoryResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsHealthCheckResponse = (boolean);