// This file is auto-generated by @hey-api/openapi-ts

export type AgentCreate = {
    name: string;
    agent_type?: (string | null);
};

export type AgentPublic = {
    name: string;
    agent_type?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type AgentsPublic = {
    data: Array<AgentPublic>;
    count: number;
};

export type AgentUpdate = {
    name?: (string | null);
    agent_type?: (string | null);
};

export type AuthorType = 'user' | 'agent';

export type BacklogItemCreate = {
    title: string;
    description?: (string | null);
    /**
     * Type: Epic, Story, Task, Sub-task
     */
    type: string;
    /**
     * Status: Backlog, Todo, Doing, Done
     */
    status: string;
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: boolean;
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    project_id: string;
};

/**
 * Public schema with parent/children for Kanban hierarchy display
 */
export type BacklogItemPublic = {
    title: string;
    description?: (string | null);
    /**
     * Type: Epic, Story, Task, Sub-task
     */
    type: string;
    /**
     * Status: Backlog, Todo, Doing, Done
     */
    status: string;
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: boolean;
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    id: string;
    project_id: string;
    created_at: string;
    updated_at: string;
    parent?: (BacklogItemSimple | null);
    children?: Array<BacklogItemSimple>;
};

/**
 * Simple schema without nested relationships to prevent recursion
 */
export type BacklogItemSimple = {
    title: string;
    description?: (string | null);
    /**
     * Type: Epic, Story, Task, Sub-task
     */
    type: string;
    /**
     * Status: Backlog, Todo, Doing, Done
     */
    status: string;
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: boolean;
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    id: string;
    project_id: string;
    created_at: string;
    updated_at: string;
};

export type BacklogItemsPublic = {
    data: Array<BacklogItemPublic>;
    count: number;
};

export type BacklogItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    type?: (string | null);
    status?: (string | null);
    rank?: (number | null);
    estimate_value?: (number | null);
    story_point?: (number | null);
    pause?: (boolean | null);
    deadline?: (string | null);
    assignee_id?: (string | null);
    reviewer_id?: (string | null);
    parent_id?: (string | null);
    project_id?: (string | null);
};

export type BlockerCreate = {
    backlog_item_id: string;
    blocker_type: string;
    description: string;
};

export type BlockerPublic = {
    id: string;
    backlog_item_id: string;
    reported_by_user_id: string;
    blocker_type: string;
    description: string;
    created_at: string;
};

export type BlockersPublic = {
    data: Array<BlockerPublic>;
    count: number;
};

export type Body_authentication_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessageCreate = {
    content: string;
    author_type: AuthorType;
    project_id: string;
    agent_id?: (string | null);
};

export type ChatMessagePublic = {
    id: string;
    project_id: string;
    author_type: AuthorType;
    user_id?: (string | null);
    agent_id?: (string | null);
    content: string;
    message_type?: (string | null);
    structured_data?: ({
    [key: string]: unknown;
} | null);
    message_metadata?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
    updated_at: string;
};

export type ChatMessagesPublic = {
    data: Array<ChatMessagePublic>;
    count: number;
};

export type ChatMessageUpdate = {
    content?: (string | null);
};

export type ConfirmCodeRequest = {
    email: string;
    /**
     * 6-digit verification code
     */
    code: string;
};

export type ConfirmCodeResponse = {
    message: string;
    user_id: string;
};

/**
 * Request schema for creating a repository from a template.
 */
export type CreateRepoFromTemplateRequest = {
    /**
     * Owner of the template repository (e.g., 'organization' or 'username')
     */
    template_owner: string;
    /**
     * Name of the template repository
     */
    template_repo: string;
    /**
     * Name for the new repository
     */
    new_repo_name: string;
    /**
     * Description for the new repository
     */
    new_repo_description?: (string | null);
    /**
     * Whether the new repository should be private
     */
    is_private?: boolean;
    /**
     * GitHub installation ID to use for creating the repository
     */
    github_installation_id: number;
};

/**
 * Response schema for repository creation.
 */
export type CreateRepoFromTemplateResponse = {
    /**
     * Whether the repository was created successfully
     */
    success: boolean;
    /**
     * GitHub repository ID
     */
    repository_id?: (number | null);
    /**
     * Name of the created repository
     */
    repository_name?: (string | null);
    /**
     * Full name of the created repository (owner/name)
     */
    repository_full_name?: (string | null);
    /**
     * URL of the created repository
     */
    repository_url?: (string | null);
    /**
     * Description of the created repository
     */
    repository_description?: (string | null);
    /**
     * Whether the repository is private
     */
    repository_private?: (boolean | null);
    /**
     * Success or error message
     */
    message?: (string | null);
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ForgotPasswordResponse = {
    message: string;
    expires_in: number;
};

export type GitHubAccountType = 'User' | 'Organization';

export type GitHubInstallationPublic = {
    installation_id: (number | null);
    account_login: string;
    account_type: GitHubAccountType;
    account_status: GitHubInstallationStatus;
    repositories?: ({
    [key: string]: unknown;
} | null);
    id: string;
    user_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type GitHubInstallationStatus = 'pending' | 'installed' | 'deleted';

export type GitHubRepositoriesPublic = {
    data: Array<GitHubRepository>;
    count: number;
};

export type GitHubRepository = {
    id: number;
    name: string;
    full_name: string;
    url: string;
    description?: (string | null);
    private: boolean;
    owner: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password?: (string | null);
    fullname?: (string | null);
    /**
     * false = credential login, true = OAuth provider login
     */
    login_provider: boolean;
};

export type LoginResponse = {
    user_id: string;
    access_token: string;
    refresh_token: string;
};

export type LogoutResponse = {
    message: string;
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new project. Code is auto-generated.
 */
export type ProjectCreate = {
    name: string;
    is_private?: boolean;
    tech_stack?: string;
    repository_url?: (string | null);
};

export type ProjectGitHubLink = {
    github_repository_id: number;
    github_repository_name: string;
    github_installation_id: string;
};

/**
 * Schema for project response with all fields from model.
 */
export type ProjectPublic = {
    id: string;
    code: string;
    name: string;
    owner_id: string;
    is_init: boolean;
    is_private: boolean;
    tech_stack: string;
    github_repository_url?: (string | null);
    github_repository_id?: (number | null);
    github_repository_name?: (string | null);
    github_installation_id?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProjectRulesCreate = {
    project_id: string;
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
};

export type ProjectRulesPublic = {
    id: string;
    project_id: string;
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProjectRulesUpdate = {
    po_prompt?: (string | null);
    dev_prompt?: (string | null);
    tester_prompt?: (string | null);
};

/**
 * Schema for list of projects response.
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * Schema for updating a project. All fields are optional.
 */
export type ProjectUpdate = {
    name?: (string | null);
    is_init?: (boolean | null);
    is_private?: (boolean | null);
    tech_stack?: (string | null);
    repository_url?: (string | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RefreshTokenResponse = {
    user_id: string;
    access_token: string;
    refresh_token: string;
};

export type RegisterRequest = {
    /**
     * Email address
     */
    email: string;
    /**
     * Full name
     */
    fullname: string;
    /**
     * Password (min 8 chars, must contain letter and number)
     */
    password: string;
    /**
     * Password confirmation
     */
    confirm_password: string;
};

export type RegisterResponse = {
    message: string;
    email: string;
    expires_in: number;
};

export type ResendCodeRequest = {
    email: string;
};

export type ResendCodeResponse = {
    message: string;
    email: string;
    expires_in: number;
};

export type ResetPasswordRequest = {
    token: string;
    new_password: string;
    confirm_password: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type Role = 'admin' | 'user';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    password: string;
    email: string;
};

export type UserPublic = {
    id: string;
    full_name?: (string | null);
    email: string;
    role: Role;
    github_installation_id?: (number | null);
    github_installations?: (Array<GitHubInstallationPublic> | null);
};

export type UserRegister = {
    username: string;
    email: string;
    password: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    email?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    username?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentsListAgentsData = {
    agentType?: (string | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
};

export type AgentsListAgentsResponse = (AgentsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentCreate;
};

export type AgentsCreateAgentResponse = (AgentPublic);

export type AgentsGetAgentData = {
    agentId: string;
};

export type AgentsGetAgentResponse = (AgentPublic);

export type AgentsUpdateAgentData = {
    agentId: string;
    requestBody: AgentUpdate;
};

export type AgentsUpdateAgentResponse = (AgentPublic);

export type AgentsDeleteAgentData = {
    agentId: string;
};

export type AgentsDeleteAgentResponse = (void);

export type AuthenticationLoginAccessTokenData = {
    formData: Body_authentication_login_access_token;
};

export type AuthenticationLoginAccessTokenResponse = (LoginResponse);

export type AuthenticationLoginData = {
    requestBody: LoginRequest;
};

export type AuthenticationLoginResponse = (LoginResponse);

export type AuthenticationRegisterData = {
    requestBody: RegisterRequest;
};

export type AuthenticationRegisterResponse = (RegisterResponse);

export type AuthenticationConfirmCodeData = {
    requestBody: ConfirmCodeRequest;
};

export type AuthenticationConfirmCodeResponse = (ConfirmCodeResponse);

export type AuthenticationResendCodeData = {
    requestBody: ResendCodeRequest;
};

export type AuthenticationResendCodeResponse = (ResendCodeResponse);

export type AuthenticationRefreshTokenData = {
    refreshToken?: string;
    requestBody: RefreshTokenRequest;
};

export type AuthenticationRefreshTokenResponse = (RefreshTokenResponse);

export type AuthenticationForgotPasswordData = {
    requestBody: ForgotPasswordRequest;
};

export type AuthenticationForgotPasswordResponse = (ForgotPasswordResponse);

export type AuthenticationResetPasswordData = {
    requestBody: ResetPasswordRequest;
};

export type AuthenticationResetPasswordResponse = (ResetPasswordResponse);

export type AuthenticationLogoutResponse = (LogoutResponse);

export type BacklogItemsGetBacklogItemsData = {
    assigneeId?: (string | null);
    limit?: number;
    projectId?: (string | null);
    skip?: number;
    status?: (string | null);
    type?: (string | null);
};

export type BacklogItemsGetBacklogItemsResponse = (BacklogItemsPublic);

export type BacklogItemsCreateBacklogItemData = {
    requestBody: BacklogItemCreate;
};

export type BacklogItemsCreateBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsGetBacklogItemData = {
    itemId: string;
};

export type BacklogItemsGetBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsUpdateBacklogItemData = {
    itemId: string;
    requestBody: BacklogItemUpdate;
};

export type BacklogItemsUpdateBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsDeleteBacklogItemData = {
    itemId: string;
};

export type BacklogItemsDeleteBacklogItemResponse = ({
    [key: string]: unknown;
});

export type BacklogItemsMoveBacklogItemData = {
    itemId: string;
    /**
     * Vị trí mới trong cột
     */
    newRank: number;
    /**
     * Cột đích (Backlog, Todo, Doing, Done)
     */
    newStatus: string;
};

export type BacklogItemsMoveBacklogItemResponse = (BacklogItemPublic);

export type BacklogItemsGetKanbanBoardData = {
    projectId: string;
};

export type BacklogItemsGetKanbanBoardResponse = (unknown);

export type BlockersCreateBlockerData = {
    requestBody: BlockerCreate;
};

export type BlockersCreateBlockerResponse = (BlockerPublic);

export type BlockersGetBlockersByBacklogItemData = {
    backlogItemId: string;
};

export type BlockersGetBlockersByBacklogItemResponse = (BlockersPublic);

export type BlockersGetBlockersByProjectData = {
    projectId: string;
};

export type BlockersGetBlockersByProjectResponse = (BlockersPublic);

export type GithubGithubWebhookResponse = ({
    [key: string]: unknown;
});

export type GithubGithubCallbackData = {
    installationId: number;
    setupAction?: (string | null);
};

export type GithubGithubCallbackResponse = (unknown);

export type GithubLinkInstallationToUserData = {
    installationId: number;
};

export type GithubLinkInstallationToUserResponse = ({
    [key: string]: unknown;
});

export type GithubListGithubRepositoriesData = {
    installationId?: (string | null);
    limit?: number;
    skip?: number;
};

export type GithubListGithubRepositoriesResponse = (GitHubRepositoriesPublic);

export type GithubLinkGithubRepositoryData = {
    projectId: string;
    requestBody: ProjectGitHubLink;
};

export type GithubLinkGithubRepositoryResponse = (ProjectPublic);

export type GithubUnlinkGithubRepositoryData = {
    projectId: string;
};

export type GithubUnlinkGithubRepositoryResponse = (ProjectPublic);

export type GithubCheckGithubInstallationStatusResponse = ({
    [key: string]: unknown;
});

export type GithubListGithubInstallationsData = {
    limit?: number;
    skip?: number;
};

export type GithubListGithubInstallationsResponse = ({
    [key: string]: unknown;
});

export type GithubCreateRepoFromTemplateEndpointData = {
    requestBody: CreateRepoFromTemplateRequest;
};

export type GithubCreateRepoFromTemplateEndpointResponse = (CreateRepoFromTemplateResponse);

export type MessagesListMessagesData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type MessagesListMessagesResponse = (ChatMessagesPublic);

export type MessagesCreateMessageData = {
    requestBody: ChatMessageCreate;
};

export type MessagesCreateMessageResponse = (ChatMessagePublic);

export type MessagesUpdateMessageData = {
    messageId: string;
    requestBody: ChatMessageUpdate;
};

export type MessagesUpdateMessageResponse = (ChatMessagePublic);

export type MessagesDeleteMessageData = {
    messageId: string;
};

export type MessagesDeleteMessageResponse = (void);

export type MessagesDeleteAllMessagesByProjectData = {
    projectId: string;
};

export type MessagesDeleteAllMessagesByProjectResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectRulesCreateProjectRulesData = {
    requestBody: ProjectRulesCreate;
};

export type ProjectRulesCreateProjectRulesResponse = (ProjectRulesPublic);

export type ProjectRulesGetProjectRulesData = {
    projectId: string;
};

export type ProjectRulesGetProjectRulesResponse = (ProjectRulesPublic);

export type ProjectRulesUpdateProjectRulesData = {
    projectId: string;
    requestBody: ProjectRulesUpdate;
};

export type ProjectRulesUpdateProjectRulesResponse = (ProjectRulesPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsHealthCheckResponse = (boolean);