"""Description of changes

Revision ID: 316d9e89f0c5
Revises: 5337a21c49c1
Create Date: 2025-11-07 16:24:24.893106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '316d9e89f0c5'
down_revision = '5337a21c49c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
