"""new change

Revision ID: 52a9559cb2a7
Revises: 7ceaf861e8dd
Create Date: 2025-11-05 15:13:25.350578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52a9559cb2a7'
down_revision = '7ceaf861e8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    githubaccounttype_enum = sa.Enum('USER', 'ORGANIZATION', name='githubaccounttype', create_type=True)
    githubaccounttype_enum.create(op.get_bind(), checkfirst=True)

    # Now alter the column to use the enum type with USING clause for casting
    op.execute("ALTER TABLE github_installations ALTER COLUMN account_type TYPE githubaccounttype USING account_type::githubaccounttype")

    # Add columns with default values to handle existing rows
    op.add_column('projects', sa.Column('is_private', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('projects', sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tech_stack')
    op.drop_column('projects', 'is_private')
    op.alter_column('github_installations', 'account_type',
               existing_type=sa.Enum('USER', 'ORGANIZATION', name='githubaccounttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
