"""Make user_id nullable in github_installations

Revision ID: 7e98c9337782
Revises: d8330df23ffd
Create Date: 2025-11-03 22:49:19.595188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e98c9337782'
down_revision = 'd8330df23ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip enum alter - account_type stays as VARCHAR
    # op.alter_column('github_installations', 'account_type',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('USER', 'ORGANIZATION', name='githubaccounttype'),
    #            existing_nullable=False)
    op.alter_column('github_installations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_installations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # Skip enum alter - account_type stays as VARCHAR
    # op.alter_column('github_installations', 'account_type',
    #            existing_type=sa.Enum('USER', 'ORGANIZATION', name='githubaccounttype'),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
