"""Add GitHub integration tables and columns

Revision ID: add_github_integration
Revises: 67643ee8d363
Create Date: 2025-11-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'add_github_integration'
down_revision = '67643ee8d363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create github_installations table
    op.create_table('github_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repositories', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', name='uq_github_installations_installation_id')
    )
    op.create_index(op.f('ix_github_installations_installation_id'), 'github_installations', ['installation_id'], unique=True)
    
    # Add GitHub columns to projects table
    op.add_column('projects', sa.Column('github_repository_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('github_repository_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projects', sa.Column('github_installation_id', sa.Uuid(), nullable=True))
    
    # Create foreign key constraint for github_installation_id
    op.create_foreign_key(
        'fk_projects_github_installation_id',
        'projects',
        'github_installations',
        ['github_installation_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    # Create unique constraint for github_repository_id
    op.create_unique_constraint('uq_projects_github_repository_id', 'projects', ['github_repository_id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop unique constraint
    op.drop_constraint('uq_projects_github_repository_id', 'projects', type_='unique')
    
    # Drop foreign key
    op.drop_constraint('fk_projects_github_installation_id', 'projects', type_='foreignkey')
    
    # Drop columns from projects
    op.drop_column('projects', 'github_installation_id')
    op.drop_column('projects', 'github_repository_name')
    op.drop_column('projects', 'github_repository_id')
    
    # Drop github_installations table
    op.drop_index(op.f('ix_github_installations_installation_id'), table_name='github_installations')
    op.drop_table('github_installations')
    
    # ### end Alembic commands ###

