"""State definitions for Retro Coordinator Agent."""

from typing import TypedDict, Optional, List, Dict

# TraDS ============= Simplified state for rules-focused retrospective
class RetroState(TypedDict):
    """Simplified state for Retro Coordinator Agent."""
    # Input
    sprint_id: str
    project_id: str
    user_feedback: Optional[str]  # Optional user feedback to refine rules

    # Sprint data
    sprint_metrics: Optional[Dict]  # Metrics from DB
    blockers: Optional[List[Dict]]  # Blockers from DB

    # Agent Reports (NEW)
    agent_reports: Optional[Dict]  # {po: str, dev: str, tester: str}

    # LLM Analysis
    what_went_well: Optional[str]  # Generated by LLM
    blockers_summary: Optional[str]  # Generated by LLM
    overview_summary: Optional[str]  # Sprint overview text

    # Project Rules (output)
    po_rules: Optional[str]
    dev_rules: Optional[str]
    tester_rules: Optional[str]

    # Final result
    retro_summary: Optional[Dict]
    error: Optional[str]
# ==============================

