"""Workspace and Git tools for Tester Agent."""

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


def commit_workspace_changes(
    workspace_path: str,
    title: str,
    branch_name: str,
    agent_name: str = "tester",
) -> dict:
    """Commit changes in workspace.
    
    Args:
        workspace_path: Path to git workspace
        title: Story/task title for commit message
        branch_name: Current branch name
        agent_name: Agent name for commit message
        
    Returns:
        dict with success status and message
    """
    if not workspace_path or not Path(workspace_path).exists():
        return {"success": False, "message": "Invalid workspace path"}
    
    try:
        # Check if there are changes to commit
        status_result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=workspace_path,
            capture_output=True,
            text=True,
            timeout=30,
        )
        
        if not status_result.stdout.strip():
            logger.info("[commit_workspace_changes] No changes to commit")
            return {"success": True, "message": "No changes to commit"}
        
        # Stage all changes
        subprocess.run(
            ["git", "add", "-A"],
            cwd=workspace_path,
            capture_output=True,
            timeout=30,
        )
        
        # Create commit message
        commit_msg = f"test({branch_name}): {title[:50]}\n\nGenerated by {agent_name} agent"
        
        # Commit
        commit_result = subprocess.run(
            ["git", "commit", "-m", commit_msg],
            cwd=workspace_path,
            capture_output=True,
            text=True,
            timeout=60,
        )
        
        if commit_result.returncode == 0:
            logger.info(f"[commit_workspace_changes] Committed: {commit_msg[:60]}")
            return {"success": True, "message": f"Committed changes: {commit_msg[:60]}"}
        else:
            logger.warning(f"[commit_workspace_changes] Commit failed: {commit_result.stderr}")
            return {"success": False, "message": commit_result.stderr[:200]}
            
    except subprocess.TimeoutExpired:
        logger.warning("[commit_workspace_changes] Git command timed out")
        return {"success": False, "message": "Git command timed out"}
    except Exception as e:
        logger.error(f"[commit_workspace_changes] Error: {e}")
        return {"success": False, "message": str(e)}


def cleanup_worktree(main_workspace: str, branch_name: str) -> bool:
    """Cleanup git worktree after task completion.
    
    Args:
        main_workspace: Path to main git repository
        branch_name: Branch name of worktree to remove
        
    Returns:
        True if cleanup successful
    """
    if not main_workspace or not branch_name:
        return False
    
    try:
        worktree_path = Path(main_workspace).parent / ".worktrees" / branch_name
        
        if not worktree_path.exists():
            return True  # Already cleaned up
        
        # Remove worktree
        result = subprocess.run(
            ["git", "worktree", "remove", str(worktree_path), "--force"],
            cwd=main_workspace,
            capture_output=True,
            timeout=60,
        )
        
        if result.returncode == 0:
            logger.info(f"[cleanup_worktree] Removed worktree: {worktree_path}")
            
            # Optionally delete branch
            subprocess.run(
                ["git", "branch", "-D", branch_name],
                cwd=main_workspace,
                capture_output=True,
                timeout=30,
            )
            return True
        else:
            logger.warning(f"[cleanup_worktree] Failed to remove worktree: {result.stderr}")
            return False
            
    except Exception as e:
        logger.error(f"[cleanup_worktree] Error: {e}")
        return False


def merge_to_main(workspace_path: str, branch_name: str, main_branch: str = "main") -> dict:
    """Merge test branch to main branch.
    
    Args:
        workspace_path: Path to workspace
        branch_name: Branch to merge
        main_branch: Target branch (default: main)
        
    Returns:
        dict with success status and message
    """
    if not workspace_path or not branch_name:
        return {"success": False, "message": "Invalid parameters"}
    
    try:
        # Checkout main
        subprocess.run(
            ["git", "checkout", main_branch],
            cwd=workspace_path,
            capture_output=True,
            timeout=30,
        )
        
        # Merge branch
        result = subprocess.run(
            ["git", "merge", branch_name, "--no-edit"],
            cwd=workspace_path,
            capture_output=True,
            text=True,
            timeout=60,
        )
        
        if result.returncode == 0:
            logger.info(f"[merge_to_main] Merged {branch_name} to {main_branch}")
            return {"success": True, "message": f"Merged {branch_name} to {main_branch}"}
        else:
            logger.warning(f"[merge_to_main] Merge failed: {result.stderr}")
            return {"success": False, "message": result.stderr[:200]}
            
    except Exception as e:
        logger.error(f"[merge_to_main] Error: {e}")
        return {"success": False, "message": str(e)}
