"""add_project_id_to_agents

Revision ID: 2a3720fc9b9a
Revises: 25b79eeac816
Create Date: 2025-11-13 15:49:58.196763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3720fc9b9a'
down_revision: Union[str, Sequence[str], None] = '25b79eeac816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('project_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_column('agents', 'project_id')
    # ### end Alembic commands ###
