"""add_sdlc_models_tech_stack_agents_projects_epics_stories

Revision ID: b62621ece33e
Revises: a0f9f0d8e849
Create Date: 2025-11-13 14:52:05.988613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62621ece33e'
down_revision: Union[str, Sequence[str], None] = 'a0f9f0d8e849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
