"""Remove WIP limit table and add wip_data column to projects

Revision ID: 069a4531ca82
Revises: ee1ef193cf71
Create Date: 2025-11-22 09:17:27.801645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '069a4531ca82'
down_revision = 'f05a3d39d58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ba_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ANALYSIS', 'BRIEF', 'SOLUTION', 'BACKLOG', 'COMPLETED', 'CANCELLED', name='basessionstatus'), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('phase_transitions', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ba_sessions_project_id'), 'ba_sessions', ['project_id'], unique=False)
    op.create_table('business_flows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('actors', sa.JSON(), nullable=True),
    sa.Column('flow_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ba_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_flows_project_id'), 'business_flows', ['project_id'], unique=False)
    op.create_index(op.f('ix_business_flows_session_id'), 'business_flows', ['session_id'], unique=False)
    op.create_table('product_briefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('product_summary', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('target_users', sa.Text(), nullable=True),
    sa.Column('product_goals', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ba_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_product_briefs_project_id'), 'product_briefs', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('PROBLEM_GOALS', 'USERS_STAKEHOLDERS', 'FEATURES_SCOPE', name='requirementcategory'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('extracted_from_message', sa.Text(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ba_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_session_id'), 'requirements', ['session_id'], unique=False)
    op.drop_index(op.f('ix_wip_limits_project'), table_name='column_wip_limits')
    op.drop_table('column_wip_limits')

    # Create enum types for add_column operations
    op.execute("CREATE TYPE epicstatus AS ENUM ('PLANNED', 'IN_PROGRESS', 'COMPLETED')")
    op.execute("CREATE TYPE storypriority AS ENUM ('HIGH', 'MEDIUM', 'LOW')")

    op.add_column('epics', sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epics', sa.Column('epic_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='epicstatus'), nullable=False))
    op.add_column('projects', sa.Column('wip_data', sa.JSON(), nullable=True))
    op.add_column('stories', sa.Column('story_priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='storypriority'), nullable=True))
    op.add_column('stories', sa.Column('dependencies', sa.JSON(), nullable=True))
    op.alter_column('stories', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('stories', 'review_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('workflow_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflow_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_policies_project'), table_name='workflow_policies')
    op.drop_constraint(op.f('uq_project_workflow'), 'workflow_policies', type_='unique')
    op.create_index(op.f('ix_workflow_policies_project_id'), 'workflow_policies', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_policies_project_id'), table_name='workflow_policies')
    op.create_unique_constraint(op.f('uq_project_workflow'), 'workflow_policies', ['project_id', 'from_status', 'to_status'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_policies_project'), 'workflow_policies', ['project_id'], unique=False)
    op.alter_column('workflow_policies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_policies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'username')
    op.alter_column('stories', 'review_started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('stories', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('stories', 'dependencies')
    op.drop_column('stories', 'story_priority')
    op.drop_column('projects', 'wip_data')
    op.drop_column('epics', 'epic_status')
    op.drop_column('epics', 'domain')

    # Drop enum types that were created for add_column operations
    op.execute("DROP TYPE IF EXISTS storypriority")
    op.execute("DROP TYPE IF EXISTS epicstatus")

    op.create_table('column_wip_limits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('wip_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('limit_type', sa.VARCHAR(length=10), server_default=sa.text("'hard'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('column_wip_limits_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('column_wip_limits_pkey')),
    sa.UniqueConstraint('project_id', 'column_name', name=op.f('uq_project_column_wip'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_wip_limits_project'), 'column_wip_limits', ['project_id'], unique=False)
    op.drop_index(op.f('ix_requirements_session_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_product_briefs_project_id'), table_name='product_briefs')
    op.drop_table('product_briefs')
    op.drop_index(op.f('ix_business_flows_session_id'), table_name='business_flows')
    op.drop_index(op.f('ix_business_flows_project_id'), table_name='business_flows')
    op.drop_table('business_flows')
    op.drop_index(op.f('ix_ba_sessions_project_id'), table_name='ba_sessions')
    op.drop_table('ba_sessions')
    # ### end Alembic commands ###
