"""add new db

Revision ID: 333049d98cdd
Revises: 
Create Date: 2025-12-11 05:47:59.112943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '333049d98cdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_stacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('stack_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_stacks_code'), 'tech_stacks', ['code'], unique=True)
    op.create_foreign_key('fk_agent_conversations_project_id', 'agent_conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_agent_executions_project_id', 'agent_executions', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('agent_persona_templates', sa.Column('avatar', sa.Text(), nullable=True))
    op.create_foreign_key('fk_agent_questions_project_id', 'agent_questions', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_agents_pool_id', 'agents', 'agent_pools', ['pool_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_agents_project_id', 'agents', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_artifacts_project_id', 'artifacts', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_epics_project_id', 'epics', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_messages_project_id', 'messages', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('orders', sa.Column('sepay_transaction_code', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('sepay_transaction_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_sepay_transaction_code'), 'orders', ['sepay_transaction_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_sepay_transaction_code'), table_name='orders')
    op.drop_column('orders', 'sepay_transaction_id')
    op.drop_column('orders', 'sepay_transaction_code')
    op.drop_constraint('fk_messages_project_id', 'messages', type_='foreignkey')
    op.drop_constraint('fk_epics_project_id', 'epics', type_='foreignkey')
    op.drop_constraint('fk_artifacts_project_id', 'artifacts', type_='foreignkey')
    op.drop_constraint('fk_agents_project_id', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agents_pool_id', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agent_questions_project_id', 'agent_questions', type_='foreignkey')
    op.drop_column('agent_persona_templates', 'avatar')
    op.drop_constraint('fk_agent_executions_project_id', 'agent_executions', type_='foreignkey')
    op.drop_constraint('fk_agent_conversations_project_id', 'agent_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_tech_stacks_code'), table_name='tech_stacks')
    op.drop_table('tech_stacks')
    # ### end Alembic commands ###
