"""add_pr_url_merge_status_to_story

Revision ID: 44a7adba6797
Revises: 29accaff9533
Create Date: 2025-12-10 18:14:35.247200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '44a7adba6797'
down_revision = '29accaff9533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_agent_conversations_project_id', 'agent_conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_agent_executions_project_id', 'agent_executions', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_agent_questions_project_id', 'agent_questions', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_agents_pool_id', 'agents', 'agent_pools', ['pool_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_agents_project_id', 'agents', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_artifacts_project_id', 'artifacts', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_epics_project_id', 'epics', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_messages_project_id', 'messages', 'projects', ['project_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('stories', sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('stories', sa.Column('merge_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'merge_status')
    op.drop_column('stories', 'pr_url')
    op.drop_constraint('fk_messages_project_id', 'messages', type_='foreignkey')
    op.drop_constraint('fk_epics_project_id', 'epics', type_='foreignkey')
    op.drop_constraint('fk_artifacts_project_id', 'artifacts', type_='foreignkey')
    op.drop_constraint('fk_agents_project_id', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agents_pool_id', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agent_questions_project_id', 'agent_questions', type_='foreignkey')
    op.drop_constraint('fk_agent_executions_project_id', 'agent_executions', type_='foreignkey')
    op.drop_constraint('fk_agent_conversations_project_id', 'agent_conversations', type_='foreignkey')
    # ### end Alembic commands ###
