"""init db

Revision ID: 5b87d30158a9
Revises: 
Create Date: 2025-12-02 16:04:24.466120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b87d30158a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metrics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('pool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_agents', sa.Integer(), nullable=False),
    sa.Column('idle_agents', sa.Integer(), nullable=False),
    sa.Column('busy_agents', sa.Integer(), nullable=False),
    sa.Column('error_agents', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('avg_execution_duration_ms', sa.Float(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('used_capacity', sa.Integer(), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=True),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metrics_snapshots_pool_name'), 'agent_metrics_snapshots', ['pool_name'], unique=False)
    op.create_index(op.f('ix_agent_metrics_snapshots_snapshot_timestamp'), 'agent_metrics_snapshots', ['snapshot_timestamp'], unique=False)
    op.create_table('agent_persona_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('communication_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'role_type', name='uq_persona_name_role')
    )
    op.create_index(op.f('ix_agent_persona_templates_name'), 'agent_persona_templates', ['name'], unique=False)
    op.create_index(op.f('ix_agent_persona_templates_role_type'), 'agent_persona_templates', ['role_type'], unique=False)
    op.create_table('epics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('epic_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='epicstatus'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_epics_project_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Integer(), nullable=True),
    sa.Column('yearly_discount_percentage', sa.Float(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('monthly_credits', sa.Integer(), nullable=True),
    sa.Column('additional_credit_price', sa.Integer(), nullable=True),
    sa.Column('available_project', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_custom_price', sa.Boolean(), nullable=False),
    sa.Column('features_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_codes', sa.JSON(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('login_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pool_type', sa.Enum('FREE', 'PAID', name='pooltype'), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('health_check_interval', sa.Integer(), nullable=False),
    sa.Column('llm_model_config', sa.JSON(), nullable=True),
    sa.Column('allowed_template_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_stopped_at', sa.DateTime(), nullable=True),
    sa.Column('total_spawned', sa.Integer(), nullable=False),
    sa.Column('total_terminated', sa.Integer(), nullable=False),
    sa.Column('current_agent_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('auto_created', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_name')
    )
    op.create_index(op.f('ix_agent_pools_is_active'), 'agent_pools', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_pools_pool_type'), 'agent_pools', ['pool_type'], unique=False)
    op.create_index(op.f('ix_agent_pools_role_type'), 'agent_pools', ['role_type'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('persona_template_id', sa.Uuid(), nullable=True),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('human_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('communication_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persona_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('created', 'starting', 'running', 'idle', 'busy', 'stopping', 'stopped', 'error', 'terminated', name='agentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['persona_template_id'], ['agent_persona_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pool_id'], ['agent_pools.id'], name='fk_agents_pool_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_agents_project_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_pool_id'), 'agents', ['pool_id'], unique=False)
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_table('linked_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_linked_accounts_user_id'), 'linked_accounts', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('parent_token_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_token_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_pool_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('tokens_per_model', sa.JSON(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('requests_per_model', sa.JSON(), nullable=True),
    sa.Column('peak_agent_count', sa.Integer(), nullable=False),
    sa.Column('avg_agent_count', sa.Float(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('avg_execution_duration_ms', sa.Float(), nullable=True),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['agent_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pool_metrics_period_start'), 'agent_pool_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_agent_pool_metrics_pool_id'), 'agent_pool_metrics', ['pool_id'], unique=False)
    op.create_table('agent_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.Enum('OPEN', 'MULTICHOICE', 'APPROVAL', name='questiontype'), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('proposed_data', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('selected_options', sa.JSON(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('modified_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('WAITING_ANSWER', 'ANSWERED', 'EXPIRED', 'CANCELLED', name='questionstatus'), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('task_context', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_agent_questions_project_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_type', sa.Enum('PRD', 'ARCHITECTURE', 'API_SPEC', 'DATABASE_SCHEMA', 'USER_STORIES', 'CODE', 'TEST_PLAN', 'REVIEW', 'ANALYSIS', name='artifacttype'), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', name='artifactstatus'), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_feedback', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_artifacts_project_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('wallet_type', sa.Text(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('used_credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.Enum('USER', 'AGENT', name='authortype'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sa.Enum('user_message', 'system_log', name='messagevisibility'), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_messages_project_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_type', sa.Enum('SUBSCRIPTION', 'CREDIT', name='ordertype'), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payos_order_code', sa.BigInteger(), nullable=True),
    sa.Column('payos_transaction_id', sa.Text(), nullable=True),
    sa.Column('payment_link_id', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('billing_cycle', sa.Text(), nullable=True),
    sa.Column('plan_code', sa.Text(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_payos_order_code'), 'orders', ['payos_order_code'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_init', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wip_data', sa.JSON(), nullable=True),
    sa.Column('project_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('active_agent_id', sa.Uuid(), nullable=True),
    sa.Column('active_agent_updated_at', sa.DateTime(), nullable=True),
    sa.Column('websocket_connected', sa.Boolean(), nullable=False),
    sa.Column('websocket_last_seen', sa.DateTime(), nullable=True),
    sa.Column('token_budget_daily', sa.Integer(), nullable=False),
    sa.Column('token_budget_monthly', sa.Integer(), nullable=False),
    sa.Column('tokens_used_today', sa.Integer(), nullable=False),
    sa.Column('tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('budget_last_reset_daily', sa.DateTime(), nullable=True),
    sa.Column('budget_last_reset_monthly', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentexecutionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_message_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_agent_executions_project_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_project_id'), 'agent_executions', ['project_id'], unique=False)
    op.create_table('credit_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('wallet_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['credit_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'VOID', name='invoicestatus'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('project_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('projectrules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('po_prompt', sa.Text(), nullable=True),
    sa.Column('dev_prompt', sa.Text(), nullable=True),
    sa.Column('tester_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('USER_STORY', 'ENABLER_STORY', name='storytype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='storystatus'), nullable=False),
    sa.Column('epic_id', sa.Uuid(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('story_point', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('agent_state', sa.Enum('PENDING', 'PROCESSING', 'CANCELED', 'FINISHED', name='storyagentstate'), nullable=True),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=True),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_project_id'), 'stories', ['project_id'], unique=False)
    op.create_table('workflow_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('required_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_policies_project_id'), 'workflow_policies', ['project_id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_agent_conversations_project_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_project_id'), 'agent_conversations', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('backlog_item_id', sa.Uuid(), nullable=False),
    sa.Column('commenter_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank_from', sa.Integer(), nullable=True),
    sa.Column('rank_to', sa.Integer(), nullable=True),
    sa.Column('estimate_from', sa.Integer(), nullable=True),
    sa.Column('estimate_to', sa.Integer(), nullable=True),
    sa.Column('deadline_from', sa.DateTime(), nullable=True),
    sa.Column('deadline_to', sa.DateTime(), nullable=True),
    sa.Column('type_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_activities')
    op.drop_table('comments')
    op.drop_index(op.f('ix_agent_conversations_project_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_workflow_policies_project_id'), table_name='workflow_policies')
    op.drop_table('workflow_policies')
    op.drop_index(op.f('ix_stories_project_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_table('projectrules')
    op.drop_table('project_preferences')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('credit_activities')
    op.drop_index(op.f('ix_agent_executions_project_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_table('projects')
    op.drop_index(op.f('ix_orders_payos_order_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('credit_wallets')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('agent_questions')
    op.drop_index(op.f('ix_agent_pool_metrics_pool_id'), table_name='agent_pool_metrics')
    op.drop_index(op.f('ix_agent_pool_metrics_period_start'), table_name='agent_pool_metrics')
    op.drop_table('agent_pool_metrics')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_linked_accounts_user_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_pool_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_pools_role_type'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_pool_type'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_is_active'), table_name='agent_pools')
    op.drop_table('agent_pools')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('epics')
    op.drop_index(op.f('ix_agent_persona_templates_role_type'), table_name='agent_persona_templates')
    op.drop_index(op.f('ix_agent_persona_templates_name'), table_name='agent_persona_templates')
    op.drop_table('agent_persona_templates')
    op.drop_index(op.f('ix_agent_metrics_snapshots_snapshot_timestamp'), table_name='agent_metrics_snapshots')
    op.drop_index(op.f('ix_agent_metrics_snapshots_pool_name'), table_name='agent_metrics_snapshots')
    op.drop_table('agent_metrics_snapshots')
    # ### end Alembic commands ###
