"""update db

Revision ID: 8071f4fa371a
Revises: 
Create Date: 2025-12-14 00:47:39.666164

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8071f4fa371a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'success', name='loglevel'), nullable=False),
    sa.Column('node', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_logs_story_id'), 'story_logs', ['story_id'], unique=False)
    op.drop_constraint(op.f('credit_wallets_subscription_id_fkey'), 'credit_wallets', type_='foreignkey')
    op.create_foreign_key(None, 'credit_wallets', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('credit_wallets_subscription_id_fkey'), 'credit_wallets', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_story_logs_story_id'), table_name='story_logs')
    op.drop_table('story_logs')
    # ### end Alembic commands ###
