"""Description of changes

Revision ID: c204442532e1
Revises: 316d9e89f0c5
Create Date: 2025-11-09 16:59:37.527021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c204442532e1'
down_revision = '316d9e89f0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectrules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('po_prompt', sa.Text(), nullable=True),
    sa.Column('dev_prompt', sa.Text(), nullable=True),
    sa.Column('tester_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('blockers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('backlog_item_id', sa.Uuid(), nullable=False),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('blocker_type', sa.Enum('DEV_BLOCKER', 'TEST_BLOCKER', name='blockertype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockers')
    op.drop_table('projectrules')
    # ### end Alembic commands ###
