"""update db

Revision ID: c3325b877905
Revises: 
Create Date: 2025-12-11 04:21:03.624162

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c3325b877905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('running_port', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('running_pid', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('stories', sa.Column('merge_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('stories', sa.Column('checkpoint_thread_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_stories_story_code'), 'stories', ['story_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_story_code'), table_name='stories')
    op.drop_column('stories', 'checkpoint_thread_id')
    op.drop_column('stories', 'merge_status')
    op.drop_column('stories', 'pr_url')
    op.drop_column('stories', 'running_pid')
    op.drop_column('stories', 'running_port')
    # ### end Alembic commands ###
