"""add agentpool table

Revision ID: d5d8e41ce9f9
Revises: b9d43806bddf
Create Date: 2025-11-27 00:30:49.933356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd5d8e41ce9f9'
down_revision = 'b9d43806bddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pool_type', sa.Enum('FREE', 'PAID', name='pooltype'), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('health_check_interval', sa.Integer(), nullable=False),
    sa.Column('llm_model_config', sa.JSON(), nullable=True),
    sa.Column('allowed_template_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_stopped_at', sa.DateTime(), nullable=True),
    sa.Column('total_spawned', sa.Integer(), nullable=False),
    sa.Column('total_terminated', sa.Integer(), nullable=False),
    sa.Column('current_agent_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('auto_created', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_name')
    )
    op.create_index(op.f('ix_agent_pools_is_active'), 'agent_pools', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_pools_pool_type'), 'agent_pools', ['pool_type'], unique=False)
    op.create_index(op.f('ix_agent_pools_role_type'), 'agent_pools', ['role_type'], unique=False)
    op.create_table('agent_pool_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('tokens_per_model', sa.JSON(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('requests_per_model', sa.JSON(), nullable=True),
    sa.Column('peak_agent_count', sa.Integer(), nullable=False),
    sa.Column('avg_agent_count', sa.Float(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('avg_execution_duration_ms', sa.Float(), nullable=True),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['agent_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pool_metrics_period_start'), 'agent_pool_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_agent_pool_metrics_pool_id'), 'agent_pool_metrics', ['pool_id'], unique=False)
    op.add_column('agents', sa.Column('pool_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_agents_pool_id'), 'agents', ['pool_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'agent_pools', ['pool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_pool_id'), table_name='agents')
    op.drop_column('agents', 'pool_id')
    op.drop_index(op.f('ix_agent_pool_metrics_pool_id'), table_name='agent_pool_metrics')
    op.drop_index(op.f('ix_agent_pool_metrics_period_start'), table_name='agent_pool_metrics')
    op.drop_table('agent_pool_metrics')
    op.drop_index(op.f('ix_agent_pools_role_type'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_pool_type'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_is_active'), table_name='agent_pools')
    op.drop_table('agent_pools')
    # ### end Alembic commands ###
