"""add BA workflow models

Revision ID: e934c3fd076a
Revises: 
Create Date: 2025-11-26 23:59:45.244574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e934c3fd076a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'credit_amount')
    op.drop_column('orders', 'auto_renew')
    op.add_column('projects', sa.Column('token_budget_daily', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('token_budget_monthly', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('tokens_used_today', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('tokens_used_this_month', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('budget_last_reset_daily', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('budget_last_reset_monthly', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'budget_last_reset_monthly')
    op.drop_column('projects', 'budget_last_reset_daily')
    op.drop_column('projects', 'tokens_used_this_month')
    op.drop_column('projects', 'tokens_used_today')
    op.drop_column('projects', 'token_budget_monthly')
    op.drop_column('projects', 'token_budget_daily')
    op.add_column('orders', sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('credit_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
