"""add BA workflow models

Revision ID: f05a3d39d58d
Revises: 
Create Date: 2025-11-22 08:57:45.800445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f05a3d39d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_wip_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=False),
    sa.Column('limit_type', sa.Enum('HARD', 'SOFT', name='limittype'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_wip_limits_project_id'), 'column_wip_limits', ['project_id'], unique=False)
    op.create_table('workflow_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('required_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_policies_project_id'), 'workflow_policies', ['project_id'], unique=False)
    op.add_column('stories', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('stories', sa.Column('review_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'review_started_at')
    op.drop_column('stories', 'started_at')
    op.drop_index(op.f('ix_workflow_policies_project_id'), table_name='workflow_policies')
    op.drop_table('workflow_policies')
    op.drop_index(op.f('ix_column_wip_limits_project_id'), table_name='column_wip_limits')
    op.drop_table('column_wip_limits')
    # ### end Alembic commands ###
