/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProjectsRouteImport } from './routes/_user/projects'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthOauthCallbackRouteImport } from './routes/_auth/oauth-callback'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as UserWorkspaceWorkspaceIdRouteImport } from './routes/_user/workspace/$workspaceId'
import { Route as UserChatChatIdRouteImport } from './routes/_user/chat/$chatId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProjectsRoute = UserProjectsRouteImport.update({
  id: '/_user/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/_admin/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWorkspaceWorkspaceIdRoute =
  UserWorkspaceWorkspaceIdRouteImport.update({
    id: '/_user/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserChatChatIdRoute = UserChatChatIdRouteImport.update({
  id: '/_user/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/projects': typeof UserProjectsRoute
  '/chat/$chatId': typeof UserChatChatIdRoute
  '/workspace/$workspaceId': typeof UserWorkspaceWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/projects': typeof UserProjectsRoute
  '/chat/$chatId': typeof UserChatChatIdRoute
  '/workspace/$workspaceId': typeof UserWorkspaceWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_layout': typeof LayoutRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_user/projects': typeof UserProjectsRoute
  '/_user/chat/$chatId': typeof UserChatChatIdRoute
  '/_user/workspace/$workspaceId': typeof UserWorkspaceWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/oauth-callback'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/projects'
    | '/chat/$chatId'
    | '/workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/oauth-callback'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/projects'
    | '/chat/$chatId'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/_admin/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/oauth-callback'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-otp'
    | '/_user/projects'
    | '/_user/chat/$chatId'
    | '/_user/workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LayoutRoute: typeof LayoutRoute
  AdminAdminRoute: typeof AdminAdminRoute
  UserProjectsRoute: typeof UserProjectsRoute
  UserChatChatIdRoute: typeof UserChatChatIdRoute
  UserWorkspaceWorkspaceIdRoute: typeof UserWorkspaceWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/projects': {
      id: '/_user/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof UserProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/oauth-callback': {
      id: '/_auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/workspace/$workspaceId': {
      id: '/_user/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof UserWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/chat/$chatId': {
      id: '/_user/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof UserChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LayoutRoute: LayoutRoute,
  AdminAdminRoute: AdminAdminRoute,
  UserProjectsRoute: UserProjectsRoute,
  UserChatChatIdRoute: UserChatChatIdRoute,
  UserWorkspaceWorkspaceIdRoute: UserWorkspaceWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
